{% set name = "unfccc_di_api" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unfccc_di_api-{{ version }}.tar.gz
  sha256: 86b53cfe274d9ea53e265d3f998dece53a0bd683618100be83e5e0603e9e32dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - pandas
    - python >=3.6
    - requests
    - treelib
    - pooch >=1.8.0
    - pyarrow
    - fake-useragent

test:
  imports:
    - unfccc_di_api
  requires:
    - pytest
  commands:
    - pytest --pyargs unfccc_di_api

about:
  home: https://github.com/pik-primap/unfccc_di_api
  summary: Python wrapper around the Flexible Query API of the UNFCCC.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://unfccc-di-api.readthedocs.io/
  dev_url: https://github.com/pik-primap/unfccc_di_api/

extra:
  recipe-maintainers:
    - mikapfl
